version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: passme123

  api:
    build: .
    ports:
      - 7000:80
    volumes:
      - .:/code
    links:
      - "db"
